# Site settings
title: Dirk Groenen - Freelance Full-stack Javascript Developer
email: dirk@bitlabs.nl
description: "A self-learned, motivated, versatile and venturous freelance software developer specialized in Javascript/Typescript, both frontend (Angular) and backend (Node.JS)."
baseurl: "/"
url: "https://dirkgroenen.nl"
github_username:  dirkgroenen

# Build settings
kramdown:
    input: GFM
permalink: /:categories/:year-:month-:day/:title/
